name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get major and minor version from package.json
        id: version
        run: |
          MAJOR=$(jq -r '.version' package.json | cut -d'.' -f1)
          MINOR=$(jq -r '.version' package.json | cut -d'.' -f2)
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "VERSION=${MAJOR}.${MINOR}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log new version
        run: |
          echo "Building version: ${{ env.VERSION }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: squikle/memit:${{ env.VERSION }}